version: "3"

services:
  db:
    container_name: postgres_db
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - "5432:5432"
    volumes: 
      - ./db/postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=
      - PGADMIN_DEFAULT_PASSWORD=
    ports:
      - 5050:80
    volumes:
       - ./db/pgadmin_data:/var/lib/pgadmin