services:
  db:
    container_name: ${POSTGRES_SERVICE_NAME}
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - todo_net
    ports:
      - ${POSTGRES_PORT}:5432
    volumes: 
      - ./db/postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - todo_net
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
       - ./db/pgadmin_data:/var/lib/pgadmin
  
  api:
    container_name: ${API_SERVICE_NAME}
    stdin_open: true
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_USER_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_SERVICE=${POSTGRES_SERVICE_NAME}
      - DATABASE_PORT=${POSTGRES_PORT}
      - DATABASE_NAME=${POSTGRES_DB}
      - API_DATABASE_URL=${API_DATABASE_URL}
      - API_SERVICE_PORT=${API_SERVICE_PORT}
      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_ACCESS_EXPIRATION_TIME=${JWT_ACCESS_EXPIRATION_TIME}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - JWT_REFRESH_EXPIRATION_TIME=${JWT_REFRESH_EXPIRATION_TIME}
      - SALT_ROUNDS=${SALT_ROUNDS}
    networks:
      - todo_net
    volumes:
      - ./api/src:/app/src
      - ./api/prisma:/app/prisma
    ports:
      - ${API_SERVICE_PORT}:${API_SERVICE_PORT}
  
  ui:
    container_name: ${UI_SERVICE_NAME}
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    environment:
      - UI_SERVICE_PORT=${UI_SERVICE_PORT}
    networks:
      - todo_net
    volumes:
      - ./ui/src:/app/src
    ports:
      - ${UI_SERVICE_PORT}:${UI_SERVICE_PORT}

networks:
  todo_net:
    driver: bridge